### CREATE
POST http://localhost:8092/workflow-rules
Content-Type: application/json

{
  "id": "6ef78bdf-6cb1-42fe-8880-ad7b15bd5ea9",
  "projectId": "12c1526f-9916-4bc8-8bed-78e66267f652",
  "userStoryStatus": "TODO",
  "maxNumberOfUserStories": 0
}

### CREATE
POST http://localhost:8092/workflow-rules
Content-Type: application/json

{
  "id": "8e912a86-5978-45f6-af58-d86169ce0a72",
  "projectId": "12c1526f-9916-4bc8-8bed-78e66267f652",
  "userStoryStatus": "IN_PROGRESS",
  "maxNumberOfUserStories": 3
}

### CREATE
POST http://localhost:8092/workflow-rules
Content-Type: application/json

{
  "id": "29cab4f1-8aee-4f73-8ca1-82b671411f69",
  "projectId": "12c1526f-9916-4bc8-8bed-78e66267f652",
  "userStoryStatus": "DONE",
  "maxNumberOfUserStories": 0
}

###
GET http://localhost:8091/user-stories

###
DELETE http://localhost:8091/user-stories


### CREATE
POST http://localhost:8091/user-stories
Content-Type: application/json

{
    "id": "7ecd47c4-892d-4493-afe1-ffc4a838cb15",
    "projectId": "12c1526f-9916-4bc8-8bed-78e66267f652",
    "title": "New US",
    "description": "This is a new user story",
    "userStoryStatus": "TODO"
}
### UPDATE
PUT http://localhost:8091/user-stories/7ecd47c4-892d-4493-afe1-ffc4a838cb15/change-status/IN_PROGRESS
Content-Type: application/json