### CREATE
POST http://localhost:8092/workflow-rules
Content-Type: application/json

{
  "id": "8e912a86-5978-45f6-af58-d86169ce0a72",
  "projectId": "12c1526f-9916-4bc8-8bed-78e66267f652",
  "userStoryStatus": "IN_PROGRESS",
  "maxNumberOfUserStories": 3
}


###
GET http://localhost:8091/user-stories

###
DELETE http://localhost:8091/user-stories


### CREATE
POST http://localhost:8091/user-stories
Content-Type: application/json

{
    "id": "7ecd47c4-892d-4493-afe1-ffc4a838cb15",
    "projectId": "12c1526f-9916-4bc8-8bed-78e66267f652",
    "title": "New US",
    "description": "This is a new user story",
    "userStoryStatus": "TODO"
}
### UPDATE
POST http://localhost:8091/user-stories/7ecd47c4-892d-4493-afe1-ffc4a838cb15/change-status
Content-Type: application/json

{
  "newStatus": "IN_PROGRESS"
}