spring:
  profiles:
    active: test
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:15432/postgres
    password: acomplexpassword
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange: survival.exchange
    queue: survival.queue
    routingKey: survival.routingKey

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: '8081'