spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: acomplexpassword
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    workflow-exchange: survival.exchange.workflow
    workflow-queue: survival.queue.workflow
    userStory-exchange: survival.exchange.userStory
    userStory-queue: survival.queue.userStory
    routingKey: survival.routingKey

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: '8091'