spring:
  profiles:
    active: test
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: acomplexpassword
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: '8080'
